version: '3.9'

services:
  web:
      container_name: fastapi
      build:
        context: services/api/
        dockerfile: Dockerfile
      ports:
        - 8005:8000
      command: uvicorn services.api.main:app --host 0.0.0.0 --reload
      volumes:
      - .:/app 