version: '3.9'

services:
  web:
      container_name: fastapi
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8080:8000
      command: uvicorn main:app --host 0.0.0.0 --reload
      volumes:
      - .:/app